name: Sync Upstream LibreTV

on:
  schedule:
    # 每天凌晨 12:00 UTC 运行
    # 如果您想在北京时间凌晨 12:00 (UTC+8) 运行，应改为 '0 16 * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/effbn/LibreTV.git
          git fetch upstream

      - name: Merge upstream into your fork
        run: |
          git merge upstream/main -m "Merge upstream changes into fork"

      - name: Push changes to your fork
        run: |
          git push origin main
